import { execFileSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { constants } from 'node:fs';
import { access, chmod, copyFile, link, lstat, mkdir, mkdtemp, readFile, readdir, realpath, rename, rm, utimes, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ASB_APP_ID, registerAppIcon } from './asb-icon.mjs';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const MARKER = `# Generated by ASB installer: ${ASB_APP_ID}`;
export const DEBIAN_DEPENDS = 'nodejs (>= 20), sqlite3, python3, python3-gi, gir1.2-gtk-4.0 (>= 4.10), gir1.2-adw-1 (>= 1.4), xdg-utils';
// Keep this list explicit. A source checkout can contain private local files.
export const RUNTIME_FILES = [
  'LICENSE', 'package.json', 'install.sh', 'uninstall.sh',
  'scripts/asb', 'scripts/asb-package.mjs', 'scripts/asb-desktop.mjs', 'scripts/asb-icon.mjs', 'scripts/asb-native.py',
  'public/switchboard.html', 'public/switchboard.css', 'public/switchboard.js', 'public/icon.svg',
  'assets/icons/local.asb.AgentSwitchBoard.svg', 'assets/icons/asb-claude-symbolic.svg', 'assets/icons/asb-openai-symbolic.svg',
  'assets/icons/README.md', 'assets/icons/ASB-disc-provenance.md',
  'src/switchboard.mjs', 'src/server.mjs', 'src/codex-data.mjs', 'src/claude-data.mjs', 'src/claude-remote-data.mjs', 'src/insights.mjs',
  'src/governance.mjs', 'src/thread-classification.mjs', 'src/token-usage.mjs', 'src/dashboard.mjs', 'src/cindy-data.mjs',
  'src/opencode-data.mjs', 'src/model-services.mjs', 'src/cindy-safe-storage.mjs', 'src/grok-quota.mjs',
  'src/bailian-quota-bridge.mjs', 'src/quota-history.mjs', 'src/notifications.mjs', 'src/pending-summary.mjs',
  'src/review-content.mjs', 'src/review-jobs.mjs', 'src/review-prompts.mjs', 'src/review-runners.mjs', 'src/search-index.mjs',
].sort();
const digest = (bytes) => createHash('sha256').update(bytes).digest('hex');
const executable = (file) => file.endsWith('.sh') || file === 'scripts/asb';
const quote = (value) => `'${value.replace(/'/g, "'\\''")}'`;

function absolute(value) {
  if (!path.isAbsolute(value) || /[\x00-\x1f\x7f]/.test(value)) throw new Error('Install paths must be absolute and have no control characters.');
  return path.resolve(value);
}
async function contents(file) {
  try {
    if (!(await lstat(file)).isFile()) throw new Error(`ASB will not change a linked or non-file path: ${file}`);
    return await readFile(file);
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}
async function safeParents(file) {
  for (let directory = path.dirname(file); directory !== path.dirname(directory); directory = path.dirname(directory)) {
    try {
      if (!(await lstat(directory)).isDirectory()) throw new Error(`ASB will not write through a linked or non-directory path: ${directory}`);
    } catch (error) { if (error.code !== 'ENOENT') throw error; }
  }
}
async function replace(file, bytes, previous, mode = 0o644) {
  const current = await contents(file);
  if (previous === null ? current !== null : !current?.equals(previous)) throw new Error(`ASB did not change a file that changed during install: ${file}`);
  const temporary = `${file}.asb-${randomUUID()}`;
  try {
    await writeFile(temporary, bytes, { flag: 'wx', mode });
    await chmod(temporary, mode);
    if (previous === null) await link(temporary, file);
    else {
      if (!(await contents(file))?.equals(previous)) throw new Error(`ASB did not change a file that changed during install: ${file}`);
      await rename(temporary, file);
    }
  } finally { await rm(temporary, { force: true }); }
}
async function version(root) {
  const value = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8')).version;
  if (!/^\d+\.\d+\.\d+$/.test(value)) throw new Error('ASB package version must use MAJOR.MINOR.PATCH.');
  return value;
}
async function copyRuntime(source, destination) {
  const hashes = {};
  for (const file of RUNTIME_FILES) {
    const bytes = await contents(path.join(source, file));
    if (!bytes) throw new Error(`Missing runtime file: ${file}`);
    const target = path.join(destination, file);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, bytes, { mode: executable(file) ? 0o755 : 0o644 });
    await chmod(target, executable(file) ? 0o755 : 0o644);
    hashes[file] = digest(bytes);
  }
  return hashes;
}
async function treeFiles(root, prefix = '') {
  const files = [];
  for (const entry of await readdir(path.join(root, prefix), { withFileTypes: true })) {
    const file = path.join(prefix, entry.name);
    if (entry.isDirectory()) files.push(...await treeFiles(root, file));
    else files.push(file);
  }
  return files.sort();
}

export async function checkRuntime() {
  if (process.platform !== 'linux' || Number(process.versions.node.split('.')[0]) < 20) throw new Error('ASB needs Linux and Node.js 20 or later.');
  let sqliteDirectory;
  try { await import('node:sqlite'); }
  catch {
    execFileSync('sqlite3', ['--version'], { stdio: 'ignore' });
    for (const directory of (process.env.PATH || '').split(path.delimiter)) {
      try { await access(path.join(directory, 'sqlite3'), constants.X_OK); sqliteDirectory = path.resolve(directory); break; }
      catch (error) { if (!['ENOENT', 'EACCES'].includes(error.code)) throw error; }
    }
  }
  const pythonExecutable = '/usr/bin/python3';
  execFileSync(pythonExecutable, ['-c', `import gi
gi.require_version('Gtk', '4.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Adw
assert (Gtk.get_major_version(), Gtk.get_minor_version()) >= (4, 10), 'GTK 4.10 or later is required.'
assert (Adw.get_major_version(), Adw.get_minor_version()) >= (1, 4), 'Libadwaita 1.4 or later is required.'
`], { stdio: 'pipe' });
  execFileSync('/usr/bin/xdg-open', ['--version'], { stdio: 'ignore' });
  return { nodeExecutable: await realpath(process.execPath), pythonExecutable, sqliteDirectory };
}

function locations(options) {
  const home = os.homedir();
  const dataDir = absolute(options.dataDir || process.env.XDG_DATA_HOME || path.join(home, '.local', 'share'));
  const binDir = absolute(options.binDir || path.join(home, '.local', 'bin'));
  return { dataDir, binDir, appDir: path.join(dataDir, 'asb'), launcher: path.join(binDir, 'asb'),
    icon: path.join(dataDir, 'icons', 'hicolor', 'scalable', 'apps', `${ASB_APP_ID}.svg`),
    desktop: path.join(dataDir, 'applications', `${ASB_APP_ID}.desktop`), manifest: path.join(dataDir, 'asb', 'install.json') };
}
async function readManifest(file) {
  const bytes = await contents(file);
  if (!bytes) return null;
  const value = JSON.parse(bytes);
  if (value.appId !== ASB_APP_ID || value.schema !== 1 || !value.releases || !value.files) throw new Error(`ASB does not own this install record: ${file}`);
  for (const [release, hashes] of Object.entries(value.releases)) {
    if (!/^\d+\.\d+\.\d+$/.test(release) || Object.entries(hashes).some(([name, hash]) => !RUNTIME_FILES.includes(name) || !/^[a-f0-9]{64}$/.test(hash))) {
      throw new Error(`Invalid ASB install record: ${file}`);
    }
  }
  return value;
}
async function verifyRelease(directory, hashes) {
  if (!(await lstat(directory)).isDirectory()) throw new Error(`ASB will not replace this release path: ${directory}`);
  if (JSON.stringify(await treeFiles(directory)) !== JSON.stringify(Object.keys(hashes).sort())) throw new Error(`ASB will not replace a release that contains other files: ${directory}`);
  for (const [file, hash] of Object.entries(hashes)) {
    await safeParents(path.join(directory, file));
    if (digest(await contents(path.join(directory, file))) !== hash) throw new Error(`ASB will not replace an edited release file: ${file}`);
  }
}

export async function install(options = {}) {
  // Check every prerequisite before creating an install directory or launcher.
  const runtime = await (options.check || checkRuntime)();
  const sourceRoot = absolute(options.sourceRoot || ROOT);
  const release = await version(sourceRoot);
  const paths = locations(options);
  const destination = path.join(paths.appDir, 'releases', release);
  for (const file of [paths.launcher, paths.manifest, paths.icon, paths.desktop, path.join(destination, 'package.json')]) await safeParents(file);
  const manifest = await readManifest(paths.manifest);
  const previous = {};
  for (const key of ['launcher', 'icon', 'desktop', 'manifest']) previous[key] = await contents(paths[key]);
  if (previous.launcher && (!manifest || digest(previous.launcher) !== manifest.files.launcher || !previous.launcher.toString().includes(MARKER))) {
    throw new Error(`ASB will not replace this launcher: ${paths.launcher}`);
  }
  const registration = await registerAppIcon({ projectRoot: sourceRoot, dataDir: paths.dataDir, launcherExecutable: paths.launcher, checkOnly: true });
  if (registration.status === 'conflict') throw new Error(registration.message);
  let existing = false;
  try {
    await lstat(destination);
    if (!manifest?.releases[release]) throw new Error(`ASB does not own this release directory: ${destination}`);
    await verifyRelease(destination, manifest.releases[release]);
    existing = true;
  } catch (error) { if (error.code !== 'ENOENT') throw error; }
  await mkdir(path.dirname(destination), { recursive: true, mode: 0o755 });
  const lock = path.join(paths.appDir, '.install-lock');
  await mkdir(lock); // Concurrent installs must not replace each other's files.
  let staging;
  const backup = `${destination}.previous-${randomUUID()}`;
  let committed = false;
  const changed = new Map();
  try {
    staging = await mkdtemp(path.join(path.dirname(destination), '.install-'));
    const hashes = await copyRuntime(sourceRoot, staging);
    await chmod(staging, 0o755);
    const wrapper = Buffer.from(`#!/bin/sh\n${MARKER}\nset -eu\nexport ASB_INSTALLED_LAUNCHER=${quote(paths.launcher)}\nexport ASB_PYTHON=${quote(runtime.pythonExecutable)}\nexport PATH=${quote([runtime.sqliteDirectory, '/usr/local/bin', '/usr/bin', '/bin'].filter(Boolean).join(':'))}:"\${PATH:-}"\nif [ "\${1:-}" = --package ]; then\n  shift\n  exec ${quote(runtime.nodeExecutable)} ${quote(path.join(destination, 'scripts', 'asb-package.mjs'))} "$@"\nfi\nexec ${quote(runtime.nodeExecutable)} ${quote(path.join(destination, 'scripts', 'asb-desktop.mjs'))} "$@"\n`);
    if (existing) await rename(destination, backup);
    await rename(staging, destination);
    committed = true;
    await mkdir(paths.binDir, { recursive: true });
    await replace(paths.launcher, wrapper, previous.launcher, 0o755);
    changed.set('launcher', wrapper);
    const result = await registerAppIcon({ projectRoot: destination, dataDir: paths.dataDir, launcherExecutable: paths.launcher });
    if (result.status === 'conflict') throw new Error(result.message);
    for (const key of ['icon', 'desktop']) changed.set(key, await readFile(paths[key]));
    const files = Object.fromEntries([...changed].map(([key, bytes]) => [key, digest(bytes)]));
    const record = { schema: 1, appId: ASB_APP_ID, version: release, releases: { ...manifest?.releases, [release]: hashes }, files };
    const recordBytes = Buffer.from(`${JSON.stringify(record, null, 2)}\n`);
    await replace(paths.manifest, recordBytes, previous.manifest, 0o600);
    changed.set('manifest', recordBytes);
    let retainedBackup;
    if (existing) { try { await rm(backup, { recursive: true }); } catch { retainedBackup = backup; } }
    return { version: release, directory: destination, launcher: paths.launcher, nodeExecutable: runtime.nodeExecutable, retainedBackup };
  } catch (error) {
    for (const [key, bytes] of [...changed].reverse()) {
      if (!(await contents(paths[key]))?.equals(bytes)) continue;
      if (previous[key] === null) await rm(paths[key], { force: true });
      else await replace(paths[key], previous[key], bytes, key === 'launcher' ? 0o755 : key === 'manifest' ? 0o600 : 0o644);
    }
    if (committed) await rm(destination, { recursive: true, force: true });
    if (existing) {
      try { await rename(backup, destination); } catch (restoreError) { if (restoreError.code !== 'ENOENT') throw restoreError; }
    }
    throw error;
  } finally {
    if (staging) await rm(staging, { recursive: true, force: true });
    await rm(lock, { recursive: true });
  }
}

export async function uninstall(options = {}) {
  const paths = locations(options);
  for (const file of [paths.launcher, paths.manifest, paths.icon, paths.desktop]) await safeParents(file);
  const manifest = await readManifest(paths.manifest);
  if (!manifest) return { removed: [], kept: [], message: 'No per-user ASB install record was found. Settings were kept.' };
  const removed = [], kept = [];
  for (const [release, hashes] of Object.entries(manifest.releases)) {
    const directory = path.join(paths.appDir, 'releases', release);
    await safeParents(path.join(directory, 'package.json'));
    try {
      await verifyRelease(directory, hashes);
      await rm(directory, { recursive: true });
      removed.push(directory);
    } catch (error) { if (error.code !== 'ENOENT') kept.push(directory); }
  }
  for (const key of ['launcher', 'icon', 'desktop']) {
    try {
      const bytes = await contents(paths[key]);
      if (!bytes) continue;
      if (digest(bytes) !== manifest.files[key]) { kept.push(paths[key]); continue; }
      await rm(paths[key]);
      removed.push(paths[key]);
    } catch { kept.push(paths[key]); }
  }
  if (!kept.length) await rm(paths.manifest);
  return { removed, kept, message: 'ASB settings, pins, and unread state were kept. Running ASB processes were not stopped.' };
}

async function normalizeTree(root, epoch) {
  await chmod(root, 0o755);
  for (const entry of await readdir(root, { withFileTypes: true })) {
    const target = path.join(root, entry.name);
    if (entry.isDirectory()) { await normalizeTree(target, epoch); await chmod(target, 0o755); }
    else if (entry.isFile()) await chmod(target, (await lstat(target)).mode & 0o111 ? 0o755 : 0o644);
    await utimes(target, epoch, epoch);
  }
  await utimes(root, epoch, epoch);
}
export async function build({ sourceRoot = ROOT, outputDir = path.join(ROOT, 'dist') } = {}) {
  const release = await version(sourceRoot);
  const epoch = Number(process.env.SOURCE_DATE_EPOCH || 0);
  if (!Number.isSafeInteger(epoch) || epoch < 0) throw new Error('SOURCE_DATE_EPOCH must be a non-negative integer.');
  const temporary = await mkdtemp(path.join(os.tmpdir(), 'asb-build-'));
  await mkdir(outputDir, { recursive: true });
  try {
    const portable = path.join(temporary, `asb-${release}`);
    await copyRuntime(sourceRoot, portable);
    await normalizeTree(portable, epoch);
    const archive = path.join(outputDir, `asb-${release}-linux.tar.gz`);
    execFileSync('tar', ['--sort=name', '--format=gnu', `--mtime=@${epoch}`, '--owner=0', '--group=0', '--numeric-owner', '-czf', archive, '-C', temporary, path.basename(portable)]);
    const debRoot = path.join(temporary, 'deb');
    const payload = path.join(debRoot, 'usr', 'lib', 'asb');
    await copyRuntime(sourceRoot, payload);
    for (const directory of ['DEBIAN', 'usr/bin', 'usr/share/applications', 'usr/share/icons/hicolor/scalable/apps', 'usr/share/doc/asb']) await mkdir(path.join(debRoot, directory), { recursive: true });
    await writeFile(path.join(debRoot, 'usr/bin/asb'), '#!/bin/sh\nexport ASB_SYSTEM_INSTALL=1\nexec /usr/lib/asb/scripts/asb "$@"\n', { mode: 0o755 });
    await copyFile(path.join(sourceRoot, 'assets/icons', `${ASB_APP_ID}.svg`), path.join(debRoot, 'usr/share/icons/hicolor/scalable/apps', `${ASB_APP_ID}.svg`));
    await copyFile(path.join(sourceRoot, 'LICENSE'), path.join(debRoot, 'usr/share/doc/asb/copyright'));
    await writeFile(path.join(debRoot, 'usr/share/applications', `${ASB_APP_ID}.desktop`), `[Desktop Entry]\nType=Application\nName=ASB\nGenericName=Agent Switch Board\nExec=/usr/bin/asb\nIcon=/usr/share/icons/hicolor/scalable/apps/${ASB_APP_ID}.svg\nTerminal=false\nStartupWMClass=${ASB_APP_ID}\nCategories=Development;\n`);
    const installedSize = Math.ceil((await Promise.all((await treeFiles(path.join(debRoot, 'usr'))).map(async (file) => (await lstat(path.join(debRoot, 'usr', file))).size))).reduce((a, b) => a + b, 0) / 1024);
    await writeFile(path.join(debRoot, 'DEBIAN/control'), `Package: asb\nVersion: ${release}\nSection: utils\nPriority: optional\nArchitecture: all\nMaintainer: ASB contributors <noreply@github.com>\nInstalled-Size: ${installedSize}\nDepends: ${DEBIAN_DEPENDS}\nHomepage: https://github.com/Jamir-boop/ASB\nDescription: Local session switch board for Codex and Claude Desktop Code\n Native GTK4 session list with local read-only provider access.\n`);
    await normalizeTree(debRoot, epoch);
    const deb = path.join(outputDir, `asb_${release}_all.deb`);
    execFileSync('dpkg-deb', ['--root-owner-group', '--threads-max=1', '--build', debRoot, deb], { env: { ...process.env, SOURCE_DATE_EPOCH: String(epoch) }, stdio: 'pipe' });
    const artifacts = [deb, archive];
    await writeFile(path.join(outputDir, 'SHA256SUMS'), (await Promise.all(artifacts.map(async (file) => `${digest(await readFile(file))}  ${path.basename(file)}\n`))).join(''));
    return artifacts;
  } finally { await rm(temporary, { recursive: true, force: true }); }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const command = process.argv[2];
  const commands = { build, install, uninstall, check: checkRuntime };
  try {
    if (!commands[command] || process.argv.length !== 3) throw new Error('Use: asb-package.mjs build|install|uninstall|check');
    console.log(JSON.stringify(await commands[command](), null, 2));
  } catch (error) {
    console.error(`ASB ${command || 'package'} failed: ${error.message}`);
    if (error.stderr) console.error(String(error.stderr).trim());
    process.exitCode = 1;
  }
}
