import { constants } from 'node:fs';
import { access, link, lstat, mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ASB_APP_ID = 'local.asb.AgentSwitchBoard';
const generated = '# Generated by ASB: local.asb.AgentSwitchBoard';
const defaultRoot = fileURLToPath(new URL('..', import.meta.url));

function absolutePath(value, name) {
  if (typeof value !== 'string' || !path.isAbsolute(value) || /[\x00-\x1f\x7f]/.test(value)) {
    throw new Error(`${name} must be an absolute path without control characters.`);
  }
  return path.resolve(value);
}

function execArgument(value) {
  // Desktop Entry string escaping is applied before Exec argument escaping.
  return `"${value.replace(/["`$\\]/g, '\\$&').replace(/\\/g, '\\\\').replace(/%/g, '%%')}"`;
}

async function existingFile(file) {
  try {
    return (await lstat(file)).isFile() ? await readFile(file) : false;
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

const same = (previous, contents) => Buffer.isBuffer(previous) && previous.equals(contents);

async function replaceFile(file, contents, previous) {
  const temporary = `${file}.asb-${randomUUID()}`;
  try {
    await writeFile(temporary, contents, { flag: 'wx', mode: 0o644 });
    if (previous === null) {
      await link(temporary, file);
    } else {
      if (!same(await existingFile(file), previous)) throw new Error(`ASB did not change ${file}: the file changed during registration.`);
      await rename(temporary, file);
    }
  } finally {
    await rm(temporary, { force: true });
  }
}

export async function registerAppIcon(options = {}) {
  const xdgData = process.env.XDG_DATA_HOME;
  const dataDir = absolutePath(options.dataDir ?? (xdgData && path.isAbsolute(xdgData) ? xdgData : path.join(os.homedir(), '.local', 'share')), 'dataDir');
  const projectRoot = absolutePath(options.projectRoot ?? defaultRoot, 'projectRoot');
  const nodeExecutable = absolutePath(options.nodeExecutable ?? process.execPath, 'nodeExecutable');
  const launcher = options.launcherExecutable
    ? absolutePath(options.launcherExecutable, 'launcherExecutable') : path.join(projectRoot, 'scripts', 'asb-desktop.mjs');
  if ((options.launcherExecutable ? launcher : nodeExecutable).includes('=')) throw new Error('The Desktop Entry executable path cannot contain "=".');
  const iconPath = path.join(dataDir, 'icons', 'hicolor', 'scalable', 'apps', `${ASB_APP_ID}.svg`);
  const desktopPath = path.join(dataDir, 'applications', `${ASB_APP_ID}.desktop`);
  const result = { iconPath, desktopPath };
  const icon = await readFile(path.join(projectRoot, 'assets', 'icons', `${ASB_APP_ID}.svg`));
  if (!options.checkOnly) await access(launcher, options.launcherExecutable ? constants.X_OK : constants.R_OK);
  if (!options.launcherExecutable) await access(nodeExecutable, constants.X_OK);
  // A file icon avoids stale GNOME Shell theme lookups after a local install.
  const command = options.launcherExecutable ? execArgument(launcher) : `${execArgument(nodeExecutable)} ${execArgument(launcher)}`;
  const desktop = Buffer.from(`[Desktop Entry]\n${generated}\nType=Application\nName=ASB\nGenericName=Agent Switch Board\nExec=${command}\nIcon=${iconPath.replace(/\\/g, '\\\\')}\nTerminal=false\nStartupWMClass=${ASB_APP_ID}\nCategories=Development;\n`);
  const previousIcon = await existingFile(iconPath);
  const previousDesktop = await existingFile(desktopPath);
  const owned = Buffer.isBuffer(previousDesktop) && previousDesktop.toString('utf8').split('\n').includes(generated);
  const conflictPath = previousDesktop !== null && !owned ? desktopPath
    : previousIcon === false || (previousIcon !== null && !owned && !same(previousIcon, icon)) ? iconPath : null;
  if (conflictPath) return { ...result, status: 'conflict', message: `ASB did not change ${conflictPath}. Rename or remove this file to register ASB.` };
  if (options.checkOnly) return { ...result, status: 'ready' };

  const files = [
    { file: iconPath, contents: icon, previous: previousIcon },
    { file: desktopPath, contents: desktop, previous: previousDesktop },
  ].filter(({ contents, previous }) => !same(previous, contents));
  const written = [];
  try {
    for (const { file } of files) await mkdir(path.dirname(file), { recursive: true });
    for (const entry of files) {
      await replaceFile(entry.file, entry.contents, entry.previous);
      written.push(entry);
    }
  } catch (error) {
    for (const { file, contents, previous } of written.reverse()) {
      if (!same(await existingFile(file), contents)) continue;
      if (previous === null) await rm(file);
      else await replaceFile(file, previous, contents);
    }
    throw error;
  }
  return { ...result, status: files.length ? previousDesktop === null ? 'installed' : 'updated' : 'unchanged' };
}
